knp_paginator:
  page_range: 5
  default_options:
    page_name: page
    sort_field_name: sort
    sort_direction_name: direction
    filter_field_name: filterParam
    filter_value_name: filterValue
    distinct: true
  template:
    pagination: "@KnpPaginator/Pagination/sliding.html.twig"
    sortable: "@KnpPaginator/Pagination/sortable_link.html.twig"
    filtration: "@KnpPaginator/Pagination/filtration.html.twig"
